#!/usr/bin/env bash

# TODO vvv
# add cachix to configuration.nix
sudo sed -i 's/.\/hardware-configuration.nix/.\/hardware-configuration.nix\n      .\/cachix.nix/g' /etc/nixos/configuration.nix
# do a rebuild
# add ./cachix.nix
# do a rebuild
# ^^^

cd ..
git clone https://github.com/fairy-tale-agi-solutions/miso
cd miso
git checkout fix
cd ../haskell-editor-setup
nix-shell --run '
  cabal update ;
  cabal install --dependencies-only'