#!/usr/bin/env bash

# add cachix to configuration.nix
# do a rebuild

# add ./cachix.nix
# do a rebuild

cd ..
git clone https://github.com/fairy-tale-agi-solutions/miso
cd miso
git checkout fix
cd ../haskell-editor-setup
nix-shell --run '
  cabal update ;
  cabal install --dependencies-only'